### ISSUE TITLE
support for more links to be used when patching?

### ISSUE THREAD

**Issue by dominater01** [GateGuy/BatchRomPatcher#2]
say you download a patch from a website like smwcentral with your tool (online not locally) like normal and instead of 1 link you could add multiple

is it possible to add this feature or would that take way to long or crash etc to be worth it?

that way its not apply 1 patch then after thats done do the steps for another link right after because atleast for me im not just grabbing 1 hack and calling it a day

**Comment by GateGuy** [comment]
It would be possible, but I don't think the people running these sites would like a program that automatically downloads a lot of things at once, even if it were only limited to a few URLs at a time. I also talked to an SMW Central admin about it a while back and he asked that I don't implement batch downloading (to be fair, if I were running a site like that, I wouldn't want a batch downloader causing so much traffic, either).

**Comment by GateGuy** [comment]
It would be possible, but I don't think the people running these sites would like a program that automatically downloads a lot of things at once, even if it were only limited to a few URLs at a time. I also talked to an SMW Central admin about it a while back and he asked that I don't implement batch downloading (to be fair, if I were running a site like that, I wouldn't want a batch downloader causing so much traffic, either).
